# Generated by /lambda — platforms/infrastructure/lambdas/user-profile-get-api
# Rule sources: .claude/rules/aws.md, .claude/rules/security.md, .claude/rules/naming.md

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# DLQ (rule: aws.md — required for async, good practice for all)
resource "aws_sqs_queue" "dlq" {
  name                      = "user-profile-get-api-${var.environment}-dlq"
  message_retention_seconds = 1209600  # 14 days

  tags = local.common_tags
}

# Execution role — least privilege (rule: security.md)
resource "aws_iam_role" "lambda_role" {
  name = "user-profile-get-api-${var.environment}-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })

  tags = local.common_tags
}

# Attach basic Lambda execution policy
resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Only the specific DynamoDB actions this function needs (rule: security.md — no *)
resource "aws_iam_role_policy" "dynamodb_policy" {
  name = "user-profile-get-api-dynamodb"
  role = aws_iam_role.lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "dynamodb:GetItem"
        ]
        Effect = "Allow"
        Resource = [
          "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/${var.table_name}"
        ]
      },
      {
        Action = [
          "xray:PutTraceSegments",
          "xray:PutTelemetryRecords"
        ]
        Effect   = "Allow"
        Resource = "*"
      }
    ]
  })
}

# Lambda function (rule: aws.md — Node 22, 512MB, 30s, X-Ray, reserved concurrency)
resource "aws_lambda_function" "handler" {
  filename      = "../dist/index.zip"
  function_name = "user-profile-get-api-${var.environment}"
  role          = aws_iam_role.lambda_role.arn
  handler       = "src/handler.handler"
  runtime       = "nodejs22.x"

  memory_size                    = 512
  timeout                        = 30
  reserved_concurrent_executions = var.environment == "prod" ? 50 : 10

  dead_letter_config {
    target_arn = aws_sqs_queue.dlq.arn
  }

  environment {
    variables = {
      TABLE_NAME   = var.table_name
      NODE_OPTIONS = "--enable-source-maps"
    }
  }

  tracing_config {
    mode = "Active"
  }

  depends_on = [
    aws_iam_role_policy_attachment.lambda_basic,
    aws_iam_role_policy.dynamodb_policy
  ]

  tags = local.common_tags

  lifecycle {
    ignore_changes = [
      filename,
      source_code_hash
    ]
  }
}

# CloudWatch Log Group (rule: aws.md — 1 month retention)
resource "aws_cloudwatch_log_group" "lambda_logs" {
  name              = "/aws/lambda/user-profile-get-api-${var.environment}"
  retention_in_days = 30

  tags = local.common_tags
}

# Local values for common tags
locals {
  common_tags = {
    Environment = var.environment
    Service     = "user-profile"
    Owner       = "platform-team"
    CostCentre  = "engineering"
  }
}

# Data source to get current AWS account ID
data "aws_caller_identity" "current" {}
