// Generated by /component UserCard

import type { Meta, StoryObj } from "@storybook/react";
import { UserCard } from "./UserCard";

const meta: Meta<typeof UserCard> = {
  title: "Design System/UserCard",
  component: UserCard,
  tags: ["autodocs"],
};
export default meta;

type Story = StoryObj<typeof UserCard>;

export const Default: Story = {
  args: {
    name:  "Jane Smith",
    email: "jane.smith@company.com",
  },
};

export const WithRole: Story = {
  args: {
    name:  "Jane Smith",
    email: "jane.smith@company.com",
    role:  "Senior Engineer",
  },
};

export const Clickable: Story = {
  args: {
    name:    "Jane Smith",
    email:   "jane.smith@company.com",
    role:    "Senior Engineer",
    onClick: () => alert("clicked"),
  },
};

export const WithAvatar: Story = {
  args: {
    name:      "Jane Smith",
    email:     "jane.smith@company.com",
    avatarUrl: "https://i.pravatar.cc/40",
  },
};
