// Generated by /component UserCard
// Rule sources: .claude/rules/design-system.md, .claude/rules/testing.md

import React from "react";
import { tokens } from "../../tokens";

export interface UserCardProps {
  name:      string;
  email:     string;
  avatarUrl?: string;
  role?:     string;
  onClick?:  () => void;
}

export function UserCard({ name, email, avatarUrl, role, onClick }: UserCardProps) {
  return (
    <div
      onClick={onClick}
      role={onClick ? "button" : undefined}
      tabIndex={onClick ? 0 : undefined}
      aria-label={onClick ? `View profile for ${name}` : undefined}
      onKeyDown={onClick ? (e) => e.key === "Enter" && onClick() : undefined}
      style={{
        display:       "flex",
        alignItems:    "center",
        gap:           tokens.space[4],
        padding:       tokens.space[4],
        background:    tokens.color.surface,
        border:        `1px solid ${tokens.color.border}`,
        borderRadius:  tokens.radius.md,
        cursor:        onClick ? "pointer" : "default",
        color:         tokens.color.text,
      }}
    >
      {/* Avatar */}
      <div
        aria-hidden="true"
        style={{
          width:        "40px",
          height:       "40px",
          borderRadius: tokens.radius.full,
          background:   tokens.color.primary,
          backgroundImage:    avatarUrl ? `url(${avatarUrl})` : undefined,
          backgroundSize:     "cover",
          backgroundPosition: "center",
          flexShrink:   0,
          display:      "flex",
          alignItems:   "center",
          justifyContent: "center",
          fontSize:     tokens.text.base,
          fontWeight:   "bold",
        }}
      >
        {!avatarUrl && name.charAt(0).toUpperCase()}
      </div>

      {/* Text */}
      <div>
        <div style={{ fontSize: tokens.text.base, fontWeight: "600" }}>{name}</div>
        <div style={{ fontSize: tokens.text.sm, color: tokens.color.textMuted }}>{email}</div>
        {role && (
          <div style={{ fontSize: tokens.text.sm, color: tokens.color.textMuted }}>{role}</div>
        )}
      </div>
    </div>
  );
}
