// Generated by /component UserCard
// Rule sources: .claude/rules/testing.md — render, interaction, a11y

import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import { axe, toHaveNoViolations } from "jest-axe";
import { UserCard } from "./UserCard";

expect.extend(toHaveNoViolations);

describe("UserCard", () => {
  const baseProps = { name: "Jane Smith", email: "jane@company.com" };

  // Render
  it("renders name and email", () => {
    render(<UserCard {...baseProps} />);
    expect(screen.getByText("Jane Smith")).toBeInTheDocument();
    expect(screen.getByText("jane@company.com")).toBeInTheDocument();
  });

  it("renders role when provided", () => {
    render(<UserCard {...baseProps} role="Senior Engineer" />);
    expect(screen.getByText("Senior Engineer")).toBeInTheDocument();
  });

  it("renders initials when no avatarUrl provided", () => {
    render(<UserCard {...baseProps} />);
    expect(screen.getByText("J")).toBeInTheDocument();
  });

  // Interaction
  it("calls onClick when clicked", () => {
    const onClick = jest.fn();
    render(<UserCard {...baseProps} onClick={onClick} />);
    fireEvent.click(screen.getByRole("button"));
    expect(onClick).toHaveBeenCalledTimes(1);
  });

  it("calls onClick when Enter is pressed", () => {
    const onClick = jest.fn();
    render(<UserCard {...baseProps} onClick={onClick} />);
    fireEvent.keyDown(screen.getByRole("button"), { key: "Enter" });
    expect(onClick).toHaveBeenCalledTimes(1);
  });

  it("does not render as button when onClick not provided", () => {
    render(<UserCard {...baseProps} />);
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
  });

  // Accessibility (rule: testing.md — every component must pass axe)
  it("has no accessibility violations (static)", async () => {
    const { container } = render(<UserCard {...baseProps} />);
    expect(await axe(container)).toHaveNoViolations();
  });

  it("has no accessibility violations (interactive)", async () => {
    const { container } = render(<UserCard {...baseProps} onClick={() => {}} />);
    expect(await axe(container)).toHaveNoViolations();
  });
});
