# Generated by /lambda — Terraform module template
# Customize: function name, environment vars, DDB table, ECS service ARNs

variable "environment" {
  description = "dev | staging | prod"
  type        = string
}

variable "function_name" {
  description = "Lambda function name (kebab-case)"
  type        = string
}

# Dead Letter Queue
resource "aws_sqs_queue" "dlq" {
  name                      = "${var.function_name}-${var.environment}-dlq"
  message_retention_seconds = 1209600

  tags = local.common_tags
}

# Execution Role
resource "aws_iam_role" "lambda_role" {
  name = "${var.function_name}-${var.environment}-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })

  tags = local.common_tags
}

# Basic execution (CloudWatch, X-Ray)
resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# X-Ray write access
resource "aws_iam_role_policy" "xray_policy" {
  name = "${var.function_name}-xray"
  role = aws_iam_role.lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = [
        "xray:PutTraceSegments",
        "xray:PutTelemetryRecords"
      ]
      Effect   = "Allow"
      Resource = "*"
    }]
  })
}

# Example: DynamoDB read permission
# Customize as needed (add S3, SQS, SNS, etc.)
variable "table_name" {
  description = "DynamoDB table name (optional)"
  type        = string
  default     = ""
}

resource "aws_iam_role_policy" "dynamodb_policy" {
  count = var.table_name != "" ? 1 : 0
  name  = "${var.function_name}-dynamodb"
  role  = aws_iam_role.lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = [
        "dynamodb:GetItem",
        "dynamodb:Query"
      ]
      Effect   = "Allow"
      Resource = "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/${var.table_name}"
    }]
  })
}

# Lambda Function
resource "aws_lambda_function" "handler" {
  filename      = "dist/index.zip"
  function_name = "${var.function_name}-${var.environment}"
  role          = aws_iam_role.lambda_role.arn
  handler       = "src/handler.handler"
  runtime       = "nodejs22.x"

  memory_size                    = 512
  timeout                        = 30
  reserved_concurrent_executions = var.environment == "prod" ? 50 : 10

  dead_letter_config {
    target_arn = aws_sqs_queue.dlq.arn
  }

  environment {
    variables = {
      NODE_OPTIONS = "--enable-source-maps"
      # Add your variables here
    }
  }

  tracing_config {
    mode = "Active"
  }

  depends_on = [
    aws_iam_role_policy_attachment.lambda_basic,
    aws_iam_role_policy.xray_policy
  ]

  tags = local.common_tags
}

# CloudWatch Log Group
resource "aws_cloudwatch_log_group" "logs" {
  name              = "/aws/lambda/${var.function_name}-${var.environment}"
  retention_in_days = 30

  tags = local.common_tags
}

# Data source
data "aws_caller_identity" "current" {}

variable "aws_region" {
  type    = string
  default = "eu-west-1"
}

locals {
  common_tags = {
    Environment = var.environment
    Owner       = "platform-team"
    CostCentre  = "engineering"
  }
}

# Outputs
output "function_arn" {
  value = aws_lambda_function.handler.arn
}

output "function_name" {
  value = aws_lambda_function.handler.function_name
}
