// Generated by /lambda — template for API-triggered Lambda
// Customize: handler name, input schema, business logic

import { APIGatewayProxyHandlerV2 } from "aws-lambda";
import { z } from "zod";

// Validation schema — define at handler boundary (rule: security.md)
const requestSchema = z.object({
  memberId: z.string().uuid("Invalid member ID"),
  // Add request fields here
});

type Request = z.infer<typeof requestSchema>;

/**
 * Main handler — validate input and route to business logic
 * Rule: Input validation at handler boundary (security.md)
 */
export const handler: APIGatewayProxyHandlerV2 = async (event) => {
  try {
    // Parse and validate
    const body = JSON.parse(event.body || "{}");
    const request = requestSchema.parse(body);

    // Call business logic
    const result = await handleRequest(request);

    return {
      statusCode: 200,
      body: JSON.stringify(result),
      headers: { "Content-Type": "application/json" },
    };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        statusCode: 400,
        body: JSON.stringify({ error: error.errors[0].message }),
        headers: { "Content-Type": "application/json" },
      };
    }

    console.error("Unhandled error:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: "Internal server error" }),
      headers: { "Content-Type": "application/json" },
    };
  }
};

/**
 * Business logic — separated from handler for testability
 */
async function handleRequest(request: Request) {
  // Implement your logic here
  return {
    memberId: request.memberId,
    processed: true,
  };
}
