// Generated by /lambda — platforms/infrastructure/lambdas/user-profile-get-api
// Rule sources: .claude/rules/security.md, .claude/rules/aws.md, .claude/rules/naming.md

import { APIGatewayProxyHandlerV2 } from "aws-lambda";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand } from "@aws-sdk/lib-dynamodb";
import { PathParamsSchema } from "./types";

// Config from environment — injected by CDK, sourced from SSM at deploy time
const config = {
  tableName: process.env.TABLE_NAME!,
  region:    process.env.AWS_REGION ?? "eu-west-1",
};

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: config.region }));

export const handler: APIGatewayProxyHandlerV2 = async (event) => {
  // 1. Validate input at boundary (rule: security.md)
  const parsed = PathParamsSchema.safeParse(event.pathParameters);
  if (!parsed.success) {
    return {
      statusCode: 400,
      body: JSON.stringify({ error: "Invalid request", details: parsed.error.flatten() }),
    };
  }

  const { userId } = parsed.data;

  // 2. Fetch from DynamoDB
  const result = await ddb.send(new GetCommand({
    TableName: config.tableName,
    Key: { pk: `USER#${userId}`, sk: "PROFILE" },
  }));

  if (!result.Item) {
    return { statusCode: 404, body: JSON.stringify({ error: "User not found" }) };
  }

  return {
    statusCode: 200,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(result.Item),
  };
};
