// Generated by /lambda — platforms/infrastructure/lambdas/user-profile-get-api
// DO NOT EDIT — re-run `/lambda user-profile-get-api` to regenerate

import { z } from "zod";

export const PathParamsSchema = z.object({
  userId: z.string().uuid("userId must be a valid UUID"),
});

export const UserProfileSchema = z.object({
  userId:    z.string().uuid(),
  email:     z.string().email(),
  name:      z.string().min(1),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type PathParams   = z.infer<typeof PathParamsSchema>;
export type UserProfile  = z.infer<typeof UserProfileSchema>;
